//Þetta er bara fyrir mig svo að ég geti lesið betur útur þessu og vitað hvernig þetta er sett upp

{
    "results":[
    {
        "eventDateName":"NEEMA",
        "name":"Tónleikar",
        "dateOfShow":"2017-04-15T21:00:00",
        "userGroupName":"Sýrland sf.",
        "eventHallName":"Café Rosenberg",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10021.jpg"},
    {
        "eventDateName":"„Inspired“ – Harold Burr – Gospel",
        "name":"„Inspired“ – Harold Burr – Gospel",
        "dateOfShow":"2017-04-19T20:00:00",
        "userGroupName":"Hannesarholt ses",
        "eventHallName":"Hljóðberg (Hannesarholt)",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10033.jpg"},
    {
        "eventDateName":"Vinir Sindra",
        "name":"Styrktartónleikar",
        "dateOfShow":"2017-04-20T19:00:00",
        "userGroupName":"Jóhann Fjalar",
        "eventHallName":"Austurbær",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10018.jpg"},        
    {
        "eventDateName":"Hammondhátíð 2017",
        "name":"Fimmtudagur",
        "dateOfShow":"2017-04-20T21:00:00",
        "userGroupName":"Hammondhátíð Djúpavogs",
        "eventHallName":"Hótel Framtíð (Djúpavogi)",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.9981.jpg"},
    {
        "eventDateName":"10 ára afmælistónleikar CVS",
        "name":"Tónleikar",
        "dateOfShow":"2017-04-20T21:00:00",
        "userGroupName":"Tröllatrú ehf",
        "eventHallName":"Græna Herbergið",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10043.jpg"},
    {
        "eventDateName":"Mannakorn",
        "name":"Aukatónleikar",
        "dateOfShow":"2017-04-21T20:30:00",
        "userGroupName":"Bæjarbíó slf",
        "eventHallName":"Bæjarbíó (Hafnarfirði)",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.9963.jpg"},
    {
        "eventDateName":"Hammondhátíð 2017",
        "name":"Föstudagur",
        "dateOfShow":"2017-04-21T21:00:00",
        "userGroupName":"Hammondhátíð Djúpavogs",
        "eventHallName":"Hótel Framtíð (Djúpavogi)",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.9981.jpg"},
     {
        "eventDateName":"10 ára afmælistónleikar CVS",
         "name":"Tónleikar",
         "dateOfShow":"2017-04-21T21:00:00",
         "userGroupName":"Tröllatrú ehf",
         "eventHallName":"Græna Herbergið",
         "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10043.jpg"},
    {
        "eventDateName":"Hammondhátíð 2017",
        "name":"Laugardagur",
        "dateOfShow":"2017-04-22T21:00:00",
        "userGroupName":"Hammondhátíð Djúpavogs",
        "eventHallName":"Hótel Framtíð (Djúpavogi)",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.9981.jpg"},
    {
        "eventDateName":"Bestu lög Björgvins",
        "name":"Stórtónleikar",
        "dateOfShow":"2017-04-22T22:00:00",
        "userGroupName":"EB Kerfi",
        "eventHallName":"Hvíta húsið (Selfossi)",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10040.jpg"},
    {
        "eventDateName":"Hammondhátíð 2017",
        "name":"Sunnudagur",
        "dateOfShow":"2017-04-23T14:00:00",
        "userGroupName":"Hammondhátíð Djúpavogs",
        "eventHallName":"Djúpavogskirkja",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.9981.jpg"},
    {
        "eventDateName":"Syngjum saman",
        "name":"Syngjum saman",
        "dateOfShow":"2017-04-23T16:00:00",
        "userGroupName":"Hannesarholt ses",
        "eventHallName":"Hljóðberg (Hannesarholt)",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10039.jpg"},
    {
        "eventDateName":"Saga Music 101",
        "name":"Frumsýning - Með súpu og drykk",
        "dateOfShow":"2017-04-26T19:30:00",
        "userGroupName":"Gamla bíó",
        "eventHallName":"Gamla Bíó Salur",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10031.jpg"},
    {
        "eventDateName":"Saga Music 101",
        "name":"Frumsýning",
        "dateOfShow":"2017-04-26T20:00:00",
        "userGroupName":"Gamla bíó",
        "eventHallName":"Gamla Bíó Salur",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10031.jpg"},
    {
        "eventDateName":"Saga Music 101",
        "name":"2. sýning - Með súpu og drykk",
        "dateOfShow":"2017-05-03T19:30:00",
        "userGroupName":"Gamla bíó",
        "eventHallName":"Gamla Bíó Salur",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10031.jpg"},
    {
        "eventDateName":"Saga Music 101",
        "name":"2. sýning",
        "dateOfShow":"2017-05-03T20:00:00",
        "userGroupName":"Gamla bíó",
        "eventHallName":"Gamla Bíó Salur",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10031.jpg"},
    {
        "eventDateName":"Saga Music 101",
        "name":"3. sýning - Með súpu og drykk",
        "dateOfShow":"2017-05-09T19:30:00",
        "userGroupName":"Gamla bíó",
        "eventHallName":"Gamla Bíó Salur",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10031.jpg"},
    {
        "eventDateName":"Saga Music 101",
        "name":"3. sýning",
        "dateOfShow":"2017-05-09T20:00:00",
        "userGroupName":"Gamla bíó",
        "eventHallName":"Gamla Bíó Salur",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10031.jpg"},
    {
        "eventDateName":"Kvartett Einars Scheving ",
        "name":"Kvartett Einars Scheving",
        "dateOfShow":"2017-05-11T20:00:00",
        "userGroupName":"Hannesarholt ses",
        "eventHallName":"Hljóðberg (Hannesarholt)",
        "imageSource":"https://d30qys758zh01z.cloudfront.net/images/medium/1.10042.jpg"}
    ]
}